// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQ1GSgH-Ej2jGoJQVmSVXUEZGvT0ttOY',
    appId: '1:805160511516:web:09dc3a7866f48c5ee297d9',
    messagingSenderId: '805160511516',
    projectId: 'billing-app-8b24a',
    authDomain: 'billing-app-8b24a.firebaseapp.com',
    storageBucket: 'billing-app-8b24a.firebasestorage.app',
    measurementId: 'G-4Q8SEZZ2Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKxpLpZseYKTd4B8-IBGbj73L4l0qVzyw',
    appId: '1:805160511516:android:2bfc93e75f7c0795e297d9',
    messagingSenderId: '805160511516',
    projectId: 'billing-app-8b24a',
    storageBucket: 'billing-app-8b24a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhiNdSdCtDzoC6Asr6E_5sfamtDw5RYF0',
    appId: '1:805160511516:ios:34679f519f9d3201e297d9',
    messagingSenderId: '805160511516',
    projectId: 'billing-app-8b24a',
    storageBucket: 'billing-app-8b24a.firebasestorage.app',
    iosBundleId: 'com.example.billingAppAtts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhiNdSdCtDzoC6Asr6E_5sfamtDw5RYF0',
    appId: '1:805160511516:ios:34679f519f9d3201e297d9',
    messagingSenderId: '805160511516',
    projectId: 'billing-app-8b24a',
    storageBucket: 'billing-app-8b24a.firebasestorage.app',
    iosBundleId: 'com.example.billingAppAtts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQ1GSgH-Ej2jGoJQVmSVXUEZGvT0ttOY',
    appId: '1:805160511516:web:a3deb07b7cf3f3d3e297d9',
    messagingSenderId: '805160511516',
    projectId: 'billing-app-8b24a',
    authDomain: 'billing-app-8b24a.firebaseapp.com',
    storageBucket: 'billing-app-8b24a.firebasestorage.app',
    measurementId: 'G-BSLDB10ZFQ',
  );
}
